### ISSUE TITLE
Potential issue with _.after

### ISSUE THREAD

**Issue by jdalton** [sanderpick/mongish#1]
Just wanted to let ya know that `_.after` has changed in Underscore 1.5+ to no longer executing the `func` immediately if `n` is `0`.

Also you might dig using [lodash](http://lodash.com/#features) instead as it works with `underscore.string`, supports exiting early in `_.each`, and can reduce some of the code you write.

For example:

``` js
// old way
 _.reject(docs, function (doc) {
  return doc.missing;
})

// new way
_.reject(docs, 'missing');

// old way
 _.each(docs, _.bind(function(d) { ....}, this));

// new way
_.each(docs, function(d) {...}, this);
```

If you'd like a PR just let me know.

**Comment by sanderpick** [comment]
Thanks for the heads up! I didn't know that _.after ever did execute the `func` immediately if when `n` is `0`. That would be nice. lodash looks cool, nice work.
